#!/usr/bin/env bash
# Concatenates all src/ headers + window.cpp into a single azbacktest.h
# Strips #pragma once and local #include "..." lines, keeps system includes
# Example strategies are NOT included

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/azbacktest.h"

{
    echo "// AZBacktest amalgamation, auto-generated by amalgamate.sh"
    echo "// Do not edit directly, modify the source files in src/ instead"
    echo "// (unless you know what you're doing, of course)"
    echo ""
    echo "// mapping is... somewhere below. Sorry! (search for kCSVMapping)"
    echo "#pragma once"
    echo ""
} > "$OUT"

# Files in dependency order
FILES=(
    # vendor
    "$SCRIPT_DIR/vendor/imgui/imconfig.h"
    "$SCRIPT_DIR/vendor/imgui/imgui.h"
    "$SCRIPT_DIR/vendor/imgui/imgui_internal.h"
    "$SCRIPT_DIR/vendor/imgui/imstb_rectpack.h"
    "$SCRIPT_DIR/vendor/imgui/imstb_textedit.h"
    "$SCRIPT_DIR/vendor/imgui/imstb_truetype.h"
    "$SCRIPT_DIR/vendor/imgui/imgui.cpp"
    "$SCRIPT_DIR/vendor/imgui/imgui_draw.cpp"
    "$SCRIPT_DIR/vendor/imgui/imgui_tables.cpp"
    "$SCRIPT_DIR/vendor/imgui/imgui_widgets.cpp"
    "$SCRIPT_DIR/vendor/imgui/backends/imgui_impl_glfw.h"
    "$SCRIPT_DIR/vendor/imgui/backends/imgui_impl_glfw.cpp"
    "$SCRIPT_DIR/vendor/imgui/backends/imgui_impl_opengl3.h"
    "$SCRIPT_DIR/vendor/imgui/backends/imgui_impl_opengl3.cpp"
    "$SCRIPT_DIR/vendor/implot/implot.h"
    "$SCRIPT_DIR/vendor/implot/implot_internal.h"
    "$SCRIPT_DIR/vendor/implot/implot.cpp"
    "$SCRIPT_DIR/vendor/implot/implot_items.cpp"
    # src
    "$SCRIPT_DIR/csvConfig.h"
    "$SCRIPT_DIR/src/marketData.h"
    "$SCRIPT_DIR/src/backtestApi.h"
    "$SCRIPT_DIR/src/window/tooling/seriesPool.h"
    "$SCRIPT_DIR/src/window/tooling/statPool.h"
    "$SCRIPT_DIR/src/initSeries.h"
    "$SCRIPT_DIR/src/window/tooling/panelManagement.h"
    "$SCRIPT_DIR/src/window/tooling/widgetManagement.h"
    "$SCRIPT_DIR/src/window/tooling/windowManagement.h"
    "$SCRIPT_DIR/src/window/window.h"
    "$SCRIPT_DIR/src/window/window.cpp"
)

for f in "${FILES[@]}"; do
    rel="${f#$SCRIPT_DIR/}"
    echo "" >> "$OUT"
    echo "// ---- $rel ----" >> "$OUT"
    # strip #pragma once and local includes, keep everything else
    sed -E '/^#pragma once/d; /^[[:space:]]*#include[[:space:]]*"/d' "$f" >> "$OUT"
done

echo "wrote $OUT"
